// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {options} from '../models';

export function FileSearch(arg1:string):Promise<Array<models.FileEntry>>;

export function Launch(arg1:models.SearchResult):Promise<void>;

export function OnSecondInstance(arg1:options.SecondInstanceData):Promise<void>;

export function RunCommand(arg1:string,arg2:string):Promise<string>;

export function Search(arg1:string):Promise<Array<models.SearchResult>>;

export function ToggleWindow():Promise<void>;
