// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Launch(arg1) {
  return window['go']['main']['App']['Launch'](arg1);
}

export function OnSecondInstance(arg1) {
  return window['go']['main']['App']['OnSecondInstance'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
