// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {options} from '../models';

export function Launch(arg1:main.SearchResult):Promise<void>;

export function OnSecondInstance(arg1:options.SecondInstanceData):Promise<void>;

export function Search(arg1:string):Promise<Array<main.SearchResult>>;

export function ToggleWindow():Promise<void>;
